SRC_URI_append = "\
	file://u-boot-2009.08-rc1-001-nosoftfloat.patch;patch=1 \
	file://u-boot-2009.08-rc1-007-tools.patch;patch=1 \
	file://u-boot-2009.08-rc1-008-Makefile.patch;patch=1 \
	file://u-boot-2009.08-rc1-009-factory.patch;patch=1 \
	file://u-boot-2009.08-rc1-010-coloured_led.patch;patch=1 \
	file://u-boot-2009.08-rc1-012-ethinit.patch;patch=1 \
	file://u-boot-2009.08-rc1-013-configs.patch;patch=1 \
	file://u-boot-2009.08-rc1-014-no-weak-inlines.patch;patch=1 \
	file://u-boot-2009.08-rc1-015-large-u-boot.patch;patch=1 \
	file://u-boot-2009.08-rc1-016-add-raise.patch;patch=1 \
	file://u-boot-2009.08-rc1-017-eabi.patch;patch=1 \
	file://u-boot-2009.08-rc2-018-sam9m10ek_and_sam9g45ek.patch;patch=1 \
	file://u-boot-2009.08-rc2-019-configs.patch;patch=1 \
	file://u-boot-2009.08-rc2-020-comment.patch;patch=1 \
	"
